server:
  port: 8090
spring:
  application:
    name: "configserver"
  profiles:
    #active: "native"
    active: "git"

  cloud:
    config:
      server:
      
        git:
          uri: https://github.com/thomassharun/config-server01.git
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: classpath:/configs

logging:
  level:
    org:
      springframework:
        cloud:
          config: DEBUG
          
management:
  endpoints:
    web:
      exposure:
        include: info, shutdown
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: configserver
    description: Config Server Application
    version: 1.0.3

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registryFetchIntervalSeconds: 1
#  instance:
#    leaseRenewalIntervalInSeconds: 1
